### ISSUE TITLE
Update README.md about SPACELIFT_API_KEY_ENDPOINT

### ISSUE THREAD

**Issue by tetienne-zenchef** [spacelift-io/setup-spacectl#13]
This warning message is displayed while running this setup.

`Environment variable "SPACELIFT_API_ENDPOINT" is deprecated, please use "SPACELIFT_API_KEY_ENDPOINT"`

**Comment by peterdeme** [comment]
Thanks for the feedback @tetienne-zenchef 🙏 
Fixed in https://github.com/spacelift-io/setup-spacectl/pull/14
